# Generated by Django 4.2.5 on 2023-11-20 13:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='father_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like_count',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(default=0, max_length=200, verbose_name='评论内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='评论创建时间'),
        ),
    ]
