# Generated by Django 4.2.5 on 2023-11-24 05:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_comment_father_id_remove_comment_like_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': '大学', 'verbose_name_plural': '大学'},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=5000, verbose_name='帖子正文'),
        ),
    ]
